### ISSUE TITLE
crash because of missing glibc version

### ISSUE THREAD

**Issue by reini-1** [Nessex/yaml2json-rs#34]
I installed latest yaml2json-rs version 0.3.1 from yaml2json-rs from https://github.com/Nessex/yaml2json-rs/releases/download/v0.3.1/yaml2json-rs-v0.3.1-x86_64-unknown-linux-gnu.tar.gz but it did not run on Ubuntu 20.04:

```shell
$ yaml2json --version
yaml2json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by yaml2json)
yaml2json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by yaml2json)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Can you tell me how to fix this?
Thanks in advance.

**Comment by Nessex** [comment]
This probably means you're missing an update to glibc. I'm running 21.04 and it's got no such issue. Looking at this page, it seems like 20.04 is still stuck on glibc 2.31:

https://launchpad.net/ubuntu/focal/+source/glibc

As another option for you, I've just added a musl-libc build which is completely static (it doesn't require any external libraries). So you could also try that version!

https://github.com/Nessex/yaml2json-rs/releases/download/v0.3.1/yaml2json-rs-v0.3.1-x86_64-unknown-linux-musl.tar.gz

I'll likely make this static version the only linux version in the future as it's more portable.

**Comment by reini-1** [comment]
20.04 is the latest Ubuntu LTS so it is maybe worth that it runs there. I checked the musl version and it seems to works.
Thanks for fixing.
